[WIP] MultiModelEditor; fixes #733; fixes #734
STARIONGROUP/COMET-WEB-Community-Edition pull request #738
Opened 2024-12-20 12:19 UTC by lxatstariongroup

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/pulls) open
- [x] I have verified that I am following the COMET-WEB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/COMET-WEB-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
MultiModelEditor; fixes #733; fixes #734

2024-12-20 12:49 UTC, samatstariongroup requested changes

2024-12-20 12:49 UTC, samatstariongroup commented on COMET.Web.Common/Utilities/CopyCreator.cs
> +}
new line at end of each file please

2024-12-20 12:49 UTC, samatstariongroup commented on COMET.Web.Common/ViewModels/Components/OpenModelViewModel.cs
> +                return Result.Fail(["The selected iteration is already openened"]);
what happens for the user? if the user should not be able to select an iteration that is already open, lets prevent them from doing so. The feedback message can stay.

2024-12-20 12:49 UTC, samatstariongroup commented on COMETwebapp/Components/MultiModelEditor/ElementDefinitionTree.razor.cs
> +            Console.WriteLine("DragEnd");
can these be implemented using a logging framework ?

2024-12-20 12:49 UTC, samatstariongroup commented on COMETwebapp/Model/Applications.cs
> +                    Name = "Multi Model Editor",
please change name to Model Editor and this one needs to replace the existing one

2024-12-20 12:49 UTC, samatstariongroup commented on COMETwebapp/Utilities/WebAppConstantValues.cs
>          public const string ModelEditorPage = "ModelEditor";
if this is the old one, i propose we replace it with the new one

2024-12-20 14:02 UTC, samatstariongroup requested changes

2024-12-20 14:02 UTC, samatstariongroup commented on COMETwebapp/ViewModels/Components/MultiModelEditor/Rows/ElementBaseTreeRowViewModel.cs
> +    {
spaces

2025-01-06 09:25 UTC, lxatstariongroup commented on COMET.Web.Common/ViewModels/Components/OpenModelViewModel.cs
> +                return Result.Fail(["The selected iteration is already openened"]);
Created issue for this: #739

2025-01-06 09:30 UTC, lxatstariongroup commented on COMETwebapp/Model/Applications.cs
> +                    Name = "Multi Model Editor",
Will be done at the end. Added a bullet in the issue for this.

2025-01-06 09:30 UTC, lxatstariongroup commented on COMETwebapp/Utilities/WebAppConstantValues.cs
>          public const string ModelEditorPage = "ModelEditor";
Will be done at the end. Added a bullet in the issue for this.

2025-01-06 09:42 UTC, lxatstariongroup commented on COMETwebapp/Components/MultiModelEditor/ElementDefinitionTree.razor.cs
> +            Console.WriteLine("DragEnd");
Done

2025-01-15 06:07 UTC, samatstariongroup approved these changes

2025-01-15 14:14 UTC, merged